<?php
// +----------------------------------------------------------------------
// | ThinkPHP [ WE CAN DO IT JUST THINK ]
// +----------------------------------------------------------------------
// | Copyright (c) 2006~2016 http://thinkphp.cn All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: liu21st <liu21st@gmail.com>
// +----------------------------------------------------------------------

return [
    '__pattern__'         => [
        'c'     => '\w+',
        'a'     => '\d+',
    ],

    'art/index'      => 'index/art/index',
    'art/read'       => 'index/art/read',
    'art/save'       => 'index/art/save',
    'art/update'     => 'index/art/update',
    'art/delete'     => 'index/art/delete',
    'chanel/index'   => 'index/chanel/index',
    'user/index'     => 'index/user/index',
    'user/read'       => 'index/user/read',
    'user/save'       => 'index/user/save',
    'user/update'     => 'index/user/update',
    'user/delete'     => 'index/user/delete',
    'session/save'    => 'index/session/save',
    'session/delete'    => 'index/session/delete',
    'resetpwd/save'     => 'index/resetpwd/save',
    'image/save'        => 'index/image/save',
    'image/read'        => 'index/image/read',
    'video/save'        => 'index/video/save',
    'dynamic/save'      => 'index/dynamic/save',
    'dynamic/index'     => 'index/dynamic/index',
    'dynamic/read'      => 'index/dynamic/read',
    'place/index'       => 'index/place/index',
    'place/read'        => 'index/place/read',
    'like/delete'       => 'index/like/delete',
    'like/save'         => 'index/like/save',
    'line/read'         => 'index/line/read',
    'line/save'         => 'index/line/save',
    'line/update'       => 'index/line/update',
    'car/index'          => 'index/car/index',
    'carauth/save'       => 'index/carauth/save',
    'carauth/delete'     => 'index/carauth/delete',
    'carauth/update'     => 'index/carauth/update',
    'artpara/save'       => 'index/artpara/save',
    'artpara/update'     => 'index/artpara/update',
    'artpara/delete'     => 'index/artpara/delete',
    'club/index'         => 'index/club/index',
    'associationUser/index'  => 'index/associationUser/index',
    'applyfriend/save'       => 'index/applyfriend/save',
    'applyfriend/index'      => 'index/applyfriend/index',
    'applyfriend/update'     => 'index/applyfriend/update',
    'location/update'        => 'index/location/update',
    'msg/index'              => 'index/msg/index',
    'msg/delete'             => 'index/msg/delete',
    'follow/save'            => 'index/follow/save',
    'follow/delete'          => 'index/follow/delete',
    'group/save'            => 'index/group/save',
    'my/read'               => 'index/my/read',
    'services/index'        => 'index/services/index',
    'bind/save'             => 'index/bind/save',
    'thirdsession/save'     => 'index/thirdsession/save',
    'comment/save'          => 'index/Comment/save',
    'comment/delete'        => 'index/Comment/delete',
    'comment/index'         => 'index/Comment/index',
    'order/save'            => 'index/Order/save',
    'order/index'           => 'index/Order/index',
    'order/read'            => 'index/Order/read',
    'order/delete'          => 'index/Order/delete',
    'actjoin/update'        => 'index/Actjoin/update',
    'rub/update'            => 'index/Rub/update',
    'pay/save'              => 'index/pay/save',
    'wallet/read'           => 'index/wallet/read',
    'ordernum/read'         => 'index/Ordernum/read',
    'msgnum/read'           => 'index/msgnum/read',
    'linemap/read'          => 'index/linemap/read',
    'orderconfirm/read'     => 'index/orderconfirm/read',
    'search/index'          => 'index/search/index',
    'test/index'            => 'index/Test/index',
    'coterie/read'          => 'index/coterie/read',
    'coterie/index'         => 'index/coterie/index',
    'vcode/save'            => 'index/vcode/save',
    'friend/delete'         => 'index/friend/delete',
    'geocoding/read'        => 'index/geocoding/read',
    'directory/index'       => 'index/directory/index',
    'photo/save'            => 'index/photo/save',
    'linecollect/index'     => 'index/linecollect/index',
    'orderweight/update'    => 'index/orderweight/update',
    'forum/read'            => 'index/forum/read',
    'version/read'          => 'index/version/read',

    'plan/save'             => 'index/plan/save',
    'plan/delete'           => 'index/plan/delete',
    'plan/update'           => 'index/plan/update',

    'pre/index'             => 'index/pre/index',

    'bindv2/save'           => 'index/bindv2/save',
//    'Callback/index'              => 'index/callback/index',

    '__rest__'=>[
        //rest风格的路由
        'address'           => 'index/address',
        'art'               => 'index/art',
        'association'       => 'index/association',
        'associationUser'   => 'index/associationUser',
        'collect'           => 'index/collect',
        'coterie'           => 'index/coterie',
        'comment'           => 'index/comment',
        'condition'         => 'index/condition',
        'chanel'            => 'index/chanel',
        'destination'       => 'index/destination',
        'follow'            => 'index/follow',
        'forum'             => 'index/forum',
        'image'             => 'index/image',
        'video'             => 'index/video',
        'line'              => 'index/line',
        'like'              => 'index/like',
        'place'             => 'index/place',
        'photo'             => 'index/photo',
        'session'           => 'index/session',
        'services'          => 'index/services',
        'search'            => 'index/search',
        'user'              => 'index/user',
        'vcode'             => 'index/vcode',
        'resetpwd'          => 'index/resetpwd',
        'car'               => 'index/car',
        'carauth'           => 'index/carauth',
        'artpara'           => 'index/artpara',
        'dynamic'           => 'index/dynamic',
        'club'              => 'index/club',
        'applyfriend'       => 'index/applyfriend',
        'location'          => 'index/location',
        'msg'               => 'index/msg',
        'group'             => 'index/group',
        'my'                => 'index/my',
        'thirdsession'      => 'index/thirdsession',
        'bind'              => 'index/bind',
        'order'             => 'index/order',
        'actjoin'           => 'index/actjoin',
        'rub'               => 'index/rub',
        'pay'               => 'index/pay',
        'wallet'            => 'index/wallet',
        'ordernum'          => 'index/ordernum',
        'msgnum'            => 'index/msgnum',
        'linemap'           => 'index/linemap',
        'orderconfirm'      => 'index/orderconfirm',
        'friend'            => 'index/friend',
        'geocoding'         => 'index/geocoding',
        'directory'         => 'index/directory',
        'linecollect'       => 'index/linecollect',
        'orderweight'       => 'index/orderweight',
        'version'           => 'index/version',
        'plan'              => 'index/plan',
        'pre'               => 'index/pre',
        'bindv2'            => 'index/bindv2',

        /******************************* 下面是测试用的，正式环境可以删除  ******************************************/

        'test'              => 'index/test',

        /*******************************            结束                ******************************************/
    ],
];
